M48
; DRILL file {KiCad (6.0.1-0)} date 2022 September 26, Monday 15:58:11
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-26T15:58:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.0669Y-2.7559
X2.0669Y-4.8425
X4.1535Y-2.7559
X4.1535Y-4.8425
T0
M30
